### ISSUE TITLE
Have some error when building SoDaRadio on Ubuntu 20.04

### ISSUE THREAD

**Issue by Po84210** [kb1vc/SoDaRadio#11]
I'm trying to build SoDaRadio from scratch on Ubuntu 20.04 following the instructions [here](https://kb1vc.github.io/SoDaRadio/). However, some error occurred in the building process:
```
[ 85%] Building CXX object src/CMakeFiles/SoDaServer.dir/GPSmon.cxx.o
/SoDaRadio/src/GPSmon.cxx: In member function 'virtual void SoDa::GPSmon::run()':
/SoDaRadio/src/GPSmon.cxx:90:44: error: invalid cast from type 'timespec_t' {aka 'timespec'} to type 'time_t' {aka 'long int'}
   90 |    time_t utc_time = (time_t) gps_data.fix.time;
      |                                            ^~~~
make[2]: *** [src/CMakeFiles/SoDaServer.dir/build.make:284: src/CMakeFiles/SoDaServer.dir/GPSmon.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:348: src/CMakeFiles/SoDaServer.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
System version: Ubuntu 20.04
Git commit: d1db867073ff1f581c2dbcb3e8dfae25c7bb9620

Could anyone help me? Thanks in advance.

**Comment by dd0vs** [comment]
Hello,
i can't really help.
There seems to be an issue with gpsd in latest ubuntu distribution. 
See this:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949214
You may check an update of gpsd or fall back to ubuntu 18.0x where it works for me.
Good Luck
DD0VS

**Comment by Po84210** [comment]
Hello @dd0vs,

Thank you very much for this information! I successfully built SoDaRadio in Docker using Ubuntu 18.04 image. As I have to run Ubuntu 20.04 at this time, I will wait until gpsd is updated.

In the meantime, I still want to try to use SoDaRadio. So, may I ask, it there a way to just disable GPS support and only build the rest of the program?

**Comment by dd0vs** [comment]
Hello,
i do not know how to safely exclude gpsd support from compilation. That question only Matt can answer?
Since the issue with gpsd is reported from begining of the year, there might be a chance to download latest sources and compile it yourself, to skip the issue?
Regards
Harald DD0VS

**Comment by kb1vc** [comment]
GPSD is a train wreck -- the developers often make backward incompatible changes to the API and, in the past, have made it difficult to figure out which API is in use.  

Let me see if I can sort this out this weekend. It should be possible to disable gpsd features -- they aren't absolutely necessary for most uses.

**Comment by kb1vc** [comment]
It looks like I've fixed this.  It has been tested on Fedora 30 and libuhd 4.0

commit log looks like this: 
```
commit 3a1fa7bef738f88b482a0ce1f3be29cc93e7ff3a (HEAD -> master, origin/master, make_gpsd_optional)
Author: Matt Reilly <kb1vc@kb1vc.org>
Date:   Thu Nov 26 12:58:47 2020 -0500

    Changes primarily to address #11 -- make using gpsdlib optional.
    
    Additionally: clean up code, try vscode (dead end), bump the patch
    version, supress some "inside baseball" developer warnings, bump some
    copyright dates, and remove boost-isms from the gui.
    
    CMakeLists.txt
    1) Address #11 to allow builders to define "DISABLE_GPSD" like this
    cmake -DDISABLE_GPSD=1 ../
    to turn off GPSD support and force HAVE_GPSLIB to false.  This cores out
    GPSmon and prevents it from tripping over some backward incompatible changes
    in the gpsd api.
    2) Disabled "package name problem" warnings that nobody can seem to figure out,
    and that are otherwise benign.
    
(and more comments)
```

**Comment by Po84210** [comment]
Hello @kb1vc,

Thank you for your commit!

I'm trying to build it on Ubuntu 20.04. But I'm still having some problems now. After I pulled this commit and then ran these commands:
```command
mkdir build
cd build
cmake -DDISABLE_GPSD=1 ../
make
```
It seems that the compiler was still trying to compile `GPSmon.cxx` and it caused the same error.

I'm sorry that I'm not familiar with CMake. I would appreciate it very much if you could tell me how to build it in the correct way.

**Comment by kb1vc** [comment]
Hmmm... This worked on Fedora ... I'm bringing up a VM with ubuntu 20.04 now, but running into a few problems.  It may take a day or so.

**Comment by kb1vc** [comment]
I've failed to get Ubuntu running in a VM -- could you send me a log of all the steps.  

Before you do the "cmake" step, please remove everything from the "build" directory.

**Comment by Po84210** [comment]
Thank you, I cleared the `build/` directory every time before I build it.

Here's my full log:
```
root@b022aeb50063:/SoDaRadio/build# rm -rf ./*

root@b022aeb50063:/SoDaRadio/build# cmake -DDISABLE_GPSD=1 ../
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SoDaRadio_VERSION=[7.0.3]
-- Found libsndfile: /usr/lib/x86_64-linux-gnu/libsndfile.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found UHD: /usr/lib/x86_64-linux-gnu/libuhd.so (Required is at least version "3.11") 
Building qt gui
-- Found Qwt: /usr/lib/libqwt-qt5.so (found version "6.1.4") 
-- Checking for one of the modules 'hamlib'
-- Checking for one of the modules 'OPTIONAL;libgps'
DISABLED GPSLIB
-- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /SoDaRadio/build

root@b022aeb50063:/SoDaRadio/build# make
Scanning dependencies of target SoDaRadio_Lib_autogen
[  1%] Automatic MOC and UIC for target SoDaRadio_Lib
[  1%] Built target SoDaRadio_Lib_autogen
[  3%] Generating ui_mainwindow.h
[  3%] Generating moc_mainwindow.cpp
[  5%] Generating moc_freqlabel.cpp
[  7%] Generating moc_soda_logtable.cpp
[  7%] Generating moc_soda_spect.cpp
[  9%] Generating moc_soda_wfall.cpp
[  9%] Generating moc_soda_comboboxes.cpp
[ 10%] Generating moc_soda_listener.cpp
[ 12%] Generating moc_soda_hamlib_server.cpp
[ 12%] Generating moc_soda_hamlib_handler.cpp
[ 14%] Generating moc_soda_hamlib_listener.cpp
[ 14%] Generating moc_soda_audio_listener.cpp
Scanning dependencies of target SoDaRadio_Lib
[ 16%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/SoDaRadio_Lib_autogen/mocs_compilation.cpp.o
[ 16%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/mainwindow.cpp.o
[ 18%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/freqlabel.cpp.o
[ 18%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_logtable.cpp.o
[ 20%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_wfall.cpp.o
[ 20%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_spect.cpp.o
[ 21%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_wfall_data.cpp.o
[ 23%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_comboboxes.cpp.o
[ 23%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_listener.cpp.o
[ 25%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/__/src/Command.cxx.o
[ 25%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_top.cpp.o
[ 27%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_mid.cpp.o
[ 29%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_loggps.cpp.o
[ 29%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_settings.cpp.o
[ 30%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_status.cpp.o
[ 30%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_bandconfig.cpp.o
[ 32%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_logeditor.cpp.o
[ 32%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_spect.cpp.o
[ 34%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/main_setup_hamlib.cpp.o
[ 36%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/__/common/Navigation.cxx.o
[ 36%] Building C object qtgui/CMakeFiles/SoDaRadio_Lib.dir/__/common/dem-gridlib.c.o
[ 38%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/__/common/GuiParams.cxx.o
[ 38%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_hamlib_server.cpp.o
[ 40%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_hamlib_handler.cpp.o
[ 41%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_hamlib_listener.cpp.o
[ 41%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/soda_audio_listener.cpp.o
[ 43%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_mainwindow.cpp.o
[ 43%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_freqlabel.cpp.o
[ 45%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_logtable.cpp.o
[ 45%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_spect.cpp.o
[ 47%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_wfall.cpp.o
[ 49%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_comboboxes.cpp.o
[ 49%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_listener.cpp.o
[ 50%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_hamlib_server.cpp.o
[ 50%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_hamlib_handler.cpp.o
[ 52%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_hamlib_listener.cpp.o
[ 54%] Building CXX object qtgui/CMakeFiles/SoDaRadio_Lib.dir/moc_soda_audio_listener.cpp.o
[ 54%] Linking CXX static library libSoDaRadio_Lib.a
[ 54%] Built target SoDaRadio_Lib
Scanning dependencies of target SoDaRadio_autogen
[ 54%] Automatic MOC and UIC for target SoDaRadio
[ 54%] Built target SoDaRadio_autogen
Scanning dependencies of target SoDaRadio
[ 56%] Building CXX object qtgui/CMakeFiles/SoDaRadio.dir/SoDaRadio_autogen/mocs_compilation.cpp.o
[ 56%] Building CXX object qtgui/CMakeFiles/SoDaRadio.dir/main_sodaradio.cpp.o
[ 58%] Linking CXX executable SoDaRadio
[ 58%] Built target SoDaRadio
Scanning dependencies of target SoDaSockets
[ 60%] Building CXX object src/CMakeFiles/SoDaSockets.dir/UDSockets.cxx.o
[ 60%] Building CXX object src/CMakeFiles/SoDaSockets.dir/IPSockets.cxx.o
[ 61%] Linking CXX static library libSoDaSockets.a
[ 61%] Built target SoDaSockets
Scanning dependencies of target accessory
[ 63%] Building CXX object src/CMakeFiles/accessory.dir/SimpleAccessory.cxx.o
[ 65%] Linking CXX shared library libaccessory.so
[ 65%] Built target accessory
Scanning dependencies of target SoDaServer
[ 67%] Building CXX object src/CMakeFiles/SoDaServer.dir/Params.cxx.o
[ 67%] Building CXX object src/CMakeFiles/SoDaServer.dir/SoDaServer.cxx.o
[ 69%] Building CXX object src/CMakeFiles/SoDaServer.dir/SoDaBase.cxx.o
[ 70%] Building CXX object src/CMakeFiles/SoDaServer.dir/SoDaThread.cxx.o
[ 70%] Building CXX object src/CMakeFiles/SoDaServer.dir/SoDaThreadRegistry.cxx.o
[ 72%] Building CXX object src/CMakeFiles/SoDaServer.dir/CWTX.cxx.o
[ 72%] Building CXX object src/CMakeFiles/SoDaServer.dir/BaseBandRX.cxx.o
[ 74%] Building CXX object src/CMakeFiles/SoDaServer.dir/BaseBandTX.cxx.o
[ 76%] Building CXX object src/CMakeFiles/SoDaServer.dir/UI.cxx.o
[ 76%] Building CXX object src/CMakeFiles/SoDaServer.dir/Command.cxx.o
[ 78%] Building CXX object src/CMakeFiles/SoDaServer.dir/OSFilter.cxx.o
[ 78%] Building CXX object src/CMakeFiles/SoDaServer.dir/HilbertTransformer.cxx.o
[ 80%] Building CXX object src/CMakeFiles/SoDaServer.dir/TDResamplerTables625x48.cxx.o
[ 81%] Building CXX object src/CMakeFiles/SoDaServer.dir/ReSampler.cxx.o
[ 81%] Building CXX object src/CMakeFiles/SoDaServer.dir/ReSamplers625x48.cxx.o
[ 83%] Building CXX object src/CMakeFiles/SoDaServer.dir/Spectrogram.cxx.o
[ 83%] Building CXX object src/CMakeFiles/SoDaServer.dir/CWGenerator.cxx.o
[ 85%] Building CXX object src/CMakeFiles/SoDaServer.dir/GPSmon.cxx.o
/SoDaRadio/src/GPSmon.cxx: In member function 'virtual void SoDa::GPSmon::run()':
/SoDaRadio/src/GPSmon.cxx:90:44: error: invalid cast from type 'timespec_t' {aka 'timespec'} to type 'time_t' {aka 'long int'}
   90 |    time_t utc_time = (time_t) gps_data.fix.time;
      |                                            ^~~~
make[2]: *** [src/CMakeFiles/SoDaServer.dir/build.make:284: src/CMakeFiles/SoDaServer.dir/GPSmon.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:348: src/CMakeFiles/SoDaServer.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by Po84210** [comment]
Perhaps it's easier and faster to use Docker container than VM for a different Linux environment?

**Comment by kb1vc** [comment]
OK.  Maybe this fixed it.  (I actually tested the compilation to make sure gpsd wasn't being included...) There was a problem in src/CMakeLists.txt that was over-riding what I'd done in the top-level CMakeLists.txt

Sorry for the iteration.  Until I get ubuntu setup reliably, I'll be dependent on "test pilots" from the ubuntu user community. ;)

73, matt

"Fixed" in commit: 
```
commit 2f08b4a65233e344135dd8d61cbc690621795f97 (HEAD -> master, origin/master)
Author: Matt Reilly <kb1vc@kb1vc.org>
Date:   Fri Nov 27 14:38:13 2020 -0500

    Fixed another issue with #11 -- GPSmon was still being built with
    calls to gpslib even when libgps was disabled with DISABLE_GPSD
    
    src/CMakeLists.txt
    Fixed setup of gpsd -- disabled if DISABLE_GPSD was set.
    
    CMakeLists.txt
    Bumped patch number.

```

**Comment by kb1vc** [comment]
I've cleaned up the GPSD related code.  The libgps folks update the API and break backward compatibility as a matter of routine.  That made the GPSmon code ugly and fragile.  It is now less ugly and fragile.  The fixes are "released" in 2b37e9bb76cc656a8aee627b58ce3337ca5ae08c and were introduced in 748a53c6d14ec7d5d6f3a166e58c418f5df872d0.
